
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 43;
  public static final int STRING_LITERAL = 66;
  public static final int GTEQ = 36;
  public static final int READLINE = 24;
  public static final int MULT = 60;
  public static final int LTEQ = 37;
  public static final int DOUBLE = 4;
  public static final int LPAREN = 54;
  public static final int PRIVATE = 29;
  public static final int CONTINUE = 19;
  public static final int INTERFACE = 8;
  public static final int INT = 3;
  public static final int MINUS = 46;
  public static final int FOR = 13;
  public static final int RPAREN = 55;
  public static final int BOOLEAN_LITERAL = 68;
  public static final int OROR = 42;
  public static final int SEMICOLON = 61;
  public static final int NOT = 49;
  public static final int LT = 35;
  public static final int READINTEGER = 23;
  public static final int COMMA = 58;
  public static final int BOOL = 5;
  public static final int CLASS = 7;
  public static final int COMP = 48;
  public static final int DIV = 47;
  public static final int ANDAND = 41;
  public static final int NEWARRAY = 21;
  public static final int PLUS = 45;
  public static final int IF = 15;
  public static final int THIS = 10;
  public static final int DOT = 51;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 44;
  public static final int RETURN = 17;
  public static final int TRUE = 32;
  public static final int NEW = 20;
  public static final int error = 1;
  public static final int EQEQ = 39;
  public static final int NULL = 9;
  public static final int MOD = 50;
  public static final int BREAK = 18;
  public static final int VOID = 2;
  public static final int EQ = 59;
  public static final int DTOI = 25;
  public static final int LBRACK = 52;
  public static final int COLON = 62;
  public static final int UNDIFIEND_TOKEN = 63;
  public static final int LBRACE = 56;
  public static final int ELSE = 16;
  public static final int PROTECTED = 31;
  public static final int RBRACK = 53;
  public static final int ITOD = 27;
  public static final int ITOB = 26;
  public static final int WHILE = 14;
  public static final int PUBLIC = 30;
  public static final int RBRACE = 57;
  public static final int EXTENDS = 11;
  public static final int BTOI = 28;
  public static final int QUESTION = 38;
  public static final int STRING = 6;
  public static final int DOUBLE_LITERAL = 65;
  public static final int FALSE = 33;
  public static final int IMPLEMENTS = 12;
  public static final int GT = 34;
  public static final int PRINT = 22;
  public static final int NOTEQ = 40;
  public static final int IDENTIFIER = 67;
  public static final int INTEGER_LITERAL = 64;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "INTERFACE",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "DTOI",
  "ITOB",
  "ITOD",
  "BTOI",
  "PRIVATE",
  "PUBLIC",
  "PROTECTED",
  "TRUE",
  "FALSE",
  "GT",
  "LT",
  "GTEQ",
  "LTEQ",
  "QUESTION",
  "EQEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "DIV",
  "COMP",
  "NOT",
  "MOD",
  "DOT",
  "LBRACK",
  "RBRACK",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "EQ",
  "MULT",
  "SEMICOLON",
  "COLON",
  "UNDIFIEND_TOKEN",
  "INTEGER_LITERAL",
  "DOUBLE_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "BOOLEAN_LITERAL"
  };
}

